ros__parameters:
    gear_ratio: [101]
    encoder_cnt: [1048576]
    joint_rated_torque: [3.45]
    torque_constant: [159000]
    controller_status: 0
    stiffness: 600.0
    damping_coeff: 181.26
    strain_gauge_factor: 2.0
    mass: 16.497
    link_length: 0.5
    f: 1.3699

